"""Tests for the rules service layer."""

import pytest

from apps.rules.services import create_rule


@pytest.mark.django_db
def test_create_rule_sets_owner_and_identifier(user):
    rule = create_rule(user=user, redirect_url="https://example.com", is_private=True)
    assert rule.created_by == user
    assert rule.is_private is True
    assert rule.redirect_identifier  # autogenerated, non-empty


@pytest.mark.django_db
def test_create_rule_identifiers_unique(user):
    a = create_rule(user=user, redirect_url="https://a.com", is_private=False)
    b = create_rule(user=user, redirect_url="https://b.com", is_private=False)
    assert a.redirect_identifier != b.redirect_identifier
