# Generated by Django 6.0.7 on 2026-07-10 18:55

import apps.rules.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('redirect_url', models.URLField(validators=[apps.rules.validators.validate_redirect_scheme])),
                ('is_private', models.BooleanField(default=False)),
                ('redirect_identifier', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created_by', '-created'], name='rules_redir_created_72416e_idx')],
            },
        ),
    ]
